# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry install
    - name: Lint with flake8
      run: |
        poetry run flake8 ./src
    - name: Lint with pylint
      run: |
        poetry run pylint --recursive y .
    - name: Check format with black
      run: |
        poetry run black --check --verbose ./src
    - name: Check documentation with sphinx
      run: |
        poetry run sphinx-build -W -b html docs docs/build
    - name: Report undocumented code with sphinx
      run: |
        poetry run python -m sphinx -M coverage docs docs/build -W
    - name: Static type check with mypy
      run: |
        poetry run mypy -p guiguts
        poetry run mypy tests
    - name: Test with pytest
      run: |
        poetry run pytest
